rvm:
  - "2.4.0"
  - "2.5.0"
gemfile:
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
install:
  - bundle install
before_script:
  - psql -c 'create database fuzzily_test;' -U postgres
  - mysql -e 'create database fuzzily_test;'
env:
  global:
    - TRAVIS=TRUE
